name: custom_element_apigen
version: 0.2.3
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Generates Dart API for JS Custom Elements
homepage: https://github.com/dart-lang/custom-element-apigen
dependencies:
  html: ">=0.12.0 <0.13.0"
  path: ">=1.0.0 <2.0.0"
  test: ^0.12.0
  yaml: ">=1.0.0 <3.0.0"
  package_resolver: "^1.0.0"
  # TODO(sigmund): maybe remove these dependencies? They are required only for
  # the generated code. We could make the codegen ensure that it is listed in
  # the package pubspec instead.
  polymer_interop: ^1.0.0-rc.1
  web_components: ^0.12.0
environment:
  sdk: '>=1.8.0 <2.0.0'
